#!/usr/bin/env bash
# script that Transfers a file from our client to a server.
# Accepts four parameters:
file_path=$1
ip_address=$2
username=$3
path_to_ssh_key=$4

if [  $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$file_path" "$username@$ip_address:~/"
fi
