#!/usr/bin/env bash
# performing a 301 code
# Update and install Nginx if not installed
if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y nginx
fi

# Configure nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

new_string = "server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Joeeazy permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
