#!/usr/bin/env bash
# changing the 404 page
# Update and install Nginx if not installed
sudo  apt-get update
sudo  apt-get install -y nginx

# Configure nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

new_string = "server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Joeeazy permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# customize the 404 pagei to Ceci n'est pas une page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocaton = \/404.html {\n\troot \/var/www/html;\n\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
