#!/usr/bin/env bash
# default decryption with my private key

# setting up the ssh agent
eval $("ssh-agent")

# location of my private key
ssh-add ~/.ssh/school

#my ip address web-01
ssh ubuntu@54.226.23.167
